### ISSUE TITLE
Broken in Xcode 6.3 beta?

### ISSUE THREAD

**Issue by jessesquires** [ArtSabintsev/PrintlnMagic#2]
Hey @ArtSabintsev - this seems to be broken in Xcode 6.3 beta for me. It looks like Xcode is using `Swift.println` instead of `PrintlnMagic.println`

I'm adding this to my project manually, not via CocoaPods. Prior to the 6.3 beta, this was working fine.

Are you seeing this behavior also?

**Comment by ArtSabintsev** [comment]
Well, I'm having a completely ridiculous issue with Xcode 6.3b1 - none of my manually-added Swift libraries are being recognized. **No such modules** errors for every library I import. Cleaning DerivedData and restarting Xcode doesn't solve the issue either.

**Comment by ArtSabintsev** [comment]
@jessesquires Confirmed that there's an issue in Xcode 6.3b1. I'll dive into it a bit deeper.

**Comment by ArtSabintsev** [comment]
I wonder if they've nixed the ability to overload Swift Standard Library methods. I'll wait it out until another beta. If that doesn't work, I'll just add a new method for statements that include all that info.

**Comment by ArtSabintsev** [comment]
I'll keep the issue open until then.

**Comment by jessesquires** [comment]
Thanks @ArtSabintsev ! I'll also report back if I find out anything new

**Comment by ArtSabintsev** [comment]
Sounds good! Thanks!

**Comment by ArtSabintsev** [comment]
As this is still an issue, I've added `magic()` as a new global function. I've updated the README as well. If Xcode 6.3 ships, and this issue continues to persist, I'll simply remove the `println()` override.

**Comment by jessesquires** [comment]
Thanks @ArtSabintsev !

**Comment by jessesquires** [comment]
Hey @ArtSabintsev - I just noticed that the following works:

````swift
MyApp.println()
````

When you specify your app target (namespace) for the overridden `println()` function, it works (i.e., calls the correct `println()`). 

This makes sense. I suspect that previous behavior was possibly a bug, and likely won't be reverted.

**Comment by ArtSabintsev** [comment]
Hey @jessesquires!

Thanks! I confirmed that that works! However, I have an edge-case :) I'm working on an app whose name space boils down to `ABC.xyz`, so doing `ABC.xyz.println("test")` doesn't fly. I'll update the README to reflect both `println()` and `magic()` methods as equivalent options.

**Comment by ArtSabintsev** [comment]
Updated the README and gave you credit in there.

Thanks so much for your diligence!

**Comment by jessesquires** [comment]
:+1:

**Comment by jessesquires** [comment]
Hey @ArtSabintsev - previous behavior now works again in Xcode 7 beta 2!

You can now override print as before.

````swift
// "PrettyPrint.swift" included in App Target
public func print<T>(object: T, _ file: String = __FILE__, _ function: String = __FUNCTION__, _ line: Int = __LINE__) {
    Swift.print("\(file.lastPathComponent.stringByDeletingPathExtension).\(function)[\(line)]: \(object)")
}

````

**Comment by ArtSabintsev** [comment]
awesome sauce! I'll make a swift 2.0 branch and get it working. Thanks for the heads up! I haven't had time to play with the beta yet, but it's on my list of things to do next month.

**Comment by ArtSabintsev** [comment]
Hey @jessesquires 

Renamed the repo from PrintlnMagic to Magic.
Deprecated PrintlnMagic in Cocoapods in favor of Magic
Pushed Magic 2.0.0 to master on Github and to Cocoapods

Code changes:
https://github.com/ArtSabintsev/Magic/blob/master/Magic.swift#L23-L29

Using NSURL for path manipulation kept failing during optional binding, so I switched to using NSString.

Thoughts?
