### ISSUE TITLE
Doesn't Log where I want it to

### ISSUE THREAD

**Issue by pixelbendr** [ArtSabintsev/PrintlnMagic#3]
I have a log file like so

static func debug(message: String, object: AnyObject) {
        if(!Config.IS_PROD){
            magic("\(message) => \(object)")
        }
  }

and I use it like so
LogUtils.debug("some message","some object")

But it logs the line in the LogUtils file. But I want it to log the line in the instantiation.

**Comment by ArtSabintsev** [comment]
Swift 1.2 broke part of PrintlnMagic. `MyAppName.println()`, where `MyAppName` is the name of you project. magic() will work again in Xcode 7.
